### ISSUE TITLE
Confusion in 139.5.60.0/22

### ISSUE THREAD

**Issue by felixonmars** [misakaio/chnroutes2#26]
It's announced by AS63199 and AS134764, but at least `139.5.60.0/2?` is located in Singapore.
![image](https://user-images.githubusercontent.com/1006477/128052602-a7a81c00-87d5-4506-a809-9201fbd24bdd.png)

![image](https://user-images.githubusercontent.com/1006477/128052828-935a7b73-2324-46ca-8510-93eaeae6cbfa.png)

**Comment by ym** [comment]
If 139.5.60.0/22 is the only visible announcement in DFZ, we won't be able to detect it. And I don't really want to add anything that can't be automated easily :-(
