### ISSUE TITLE
194.246.96.0/24 should be removed

### ISSUE THREAD

**Issue by felixonmars** [misakaio/chnroutes2#31]
AS31529 DENIC-ANYCAST-AS - DENIC eG, DE

It's actually located in DE and doesn't anycast to China mainland.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1006477/183380687-fbd4f1a3-6f71-4210-a73c-08f57b372228.png">

**Comment by ym** [comment]
It's announced through CSTNET but we'll remove it from the list.

```
	BGP.as_path: 57695 57695 174 7497 24151 31529
	BGP.as_path: 57695 57695 48024 60068 3491 7497 24151 31529
	BGP.as_path: 57695 57695 60068 3491 7497 24151 31529
	BGP.as_path: 57695 57695 60068 3491 7497 24151 31529
	BGP.as_path: 57695 57695 60068 3491 7497 24151 31529
	BGP.as_path: 57695 57695 174 7497 24151 31529
	BGP.as_path: 57695 57695 60068 174 7497 24151 31529
```
