### ISSUE TITLE
美团域名，需要调整

### ISSUE THREAD

**Issue by asdfj2381k** [misakaio/chnroutes2#35]
http://metrics-picture.d.meituan.net:443

没被geo ip cn拦截到，走到FINAL去了。

![image](https://user-images.githubusercontent.com/56584082/187206291-d9d06717-8c0f-4906-9666-fe8a43e7d8cc.png)

**Comment by tutugreen** [comment]
DNS Non-existent domain 欸。

**Comment by asdfj2381k** [comment]
> DNS Non-existent domain 欸。

不好意思，我没看明白，网络知识不太足够。  

是需要我这边调整些什么吗？

**Comment by tutugreen** [comment]
纯路过，只是发现

metrics-picture.d.meituan.net

[目前解析不出来](https://dnschecker.org/all-dns-records-of-domain.php?query=metrics-picture.d.meituan.net&rtype=ALL&dns=google)

**Comment by nasaboy** [comment]
这个是美团自己的bug，可以把d.meituan.net加到real-ip里
