### ISSUE TITLE
Some IP ranges are only routable in China Mainland and not included

### ISSUE THREAD

**Issue by felixonmars** [misakaio/chnroutes2#4]
For example:

103.53.126.51 (resolved from lx3.cok.elexapp.com)

**Comment by felixonmars** [comment]
Didn't find new ranges for some time... Maybe consider to add a separate list to maintain manually?

103.53.124.0/22 should be part of it.

**Comment by ym** [comment]
That's possible but I think it's better to get a BGP feed from CT or CU instead.

**Comment by felixonmars** [comment]
Another example:

150.242.122.204/22

Only routable in CERNET.

**Comment by ym** [comment]
These two cases are fixed.

We added a feed including CMI and somehow these prefixes are visible from CMI customer view.

**Comment by felixonmars** [comment]
Thanks a lot!
