### ISSUE TITLE
[请求增加IP段] 上海市 139.217.128.0/17、139.219.128.0/17

### ISSUE THREAD

**Issue by phantastar** [misakaio/chnroutes2#46]
以上两个IP段位于上海市，数据库中还没有，请求加入

DNS：h3://223.5.5.5/dns-query

复现步骤：
1，解析www.memobird.cn得出139.217.201.114 / 解析study.memobird.cn得出139.219.193.203 / 解析w.memobird.cn得出139.219.228.164 
2，未命中IP段（所以未直连）
3，经确认无法从海外发起访问
![image](https://github.com/misakaio/chnroutes2/assets/25948362/ddf7100e-e632-4a8e-81b9-5cdc1ca5c599)
![image](https://github.com/misakaio/chnroutes2/assets/25948362/657cd5f6-b31b-4f90-8a9a-8e5fdb891f0a)

**Comment by ym** [comment]
`139.217.128.0/17` also has an upstream outside of China. That's why we didn't include it in the list.
